main_vpc_cidr_block    = "10.0.0.0/16"
main_subnet_cidr_block = "10.0.1.0/24"
vpc_name               = "VPC Development"
subnet_name            = "Subnet Development"
key_name               = "name"
key_location           = "path"
